#!/usr/bin/env python3

import argparse
import fileop
import player
import search

def parseArgs(args):
    parse_dict = vars(args)
    if parse_dict['add'] != None:
        str_input = ' '.join(parse_dict['add'])
        splitted_input = str_input.split('/')
        for item in splitted_input:
            w_input = item.replace(' ','+')
            my_url = search.singleUrl(w_input)
            fileop.addLink(my_url)
    elif parse_dict['search'] != None:
        str_input = '+'.join(parse_dict['search'])
        url_list = search.multiUrl(str_input)
        for item in url_list:
            fileop.addLink(item)
    elif parse_dict['remove'] != 0:
        sel_num = parse_dict['remove']
        fileop.removeSelected(sel_num)
    elif parse_dict['play'] == True:
        player.start()
    elif parse_dict['clear'] == True:
        fileop.removeDict()
    elif parse_dict['view'] == True:
        fileop.dataViewer()
    else:
        print('[WARN] Error with parse')

def main():
    parser = argparse.ArgumentParser(description='Simple script to stream audio from youtube')
    parser.add_argument('-a', '--add', type=str, nargs='*',
                        help='Add url to queue')
    parser.add_argument('-s', '--search', type=str, nargs='*',
                        help='Search for a song')
    parser.add_argument('-r', '--remove', type=int, default=0,
                        help='Remove selected song')
    parser.add_argument('-p', '--play', action='store_true', default=False,
                        help='Play songs in queue')
    parser.add_argument('-rl', '--remove-last', action='store_true', default=False, 
                        help='Remove last song from list')
    parser.add_argument('-c', '--clear', action='store_true', default=False,
                        help='Clear queue')
    parser.add_argument('-v', '--view', action='store_true', default=False,
                        help='View song in queue')
    args = parser.parse_args()
    fileop.jsonCheck()
    parseArgs(args) 

if __name__ == '__main__':
    main()

