#!/usr/bin/env python3

import argparse
import fileop
import player
import search

def parseArgs(args):
    parse_dict = vars(args)
    if parse_dict['add'] != None:
        w_input = '+'.join( parse_dict['add'])
        my_url = search.generateUrl(w_input)
        fileop.addLink(my_url)
    elif parse_dict['remove_last'] == True:
        fileop.clearDict()
    elif parse_dict['play'] == True:
        player.start()
    elif parse_dict['clear'] == True:
        fileop.clearDict()
    elif parse_dict['view'] == True:
        fileop.dataViewer()
    else:
        print('[WARN] Error with parse')

def main():
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('-a', '--add', type=str, nargs='*',
                        help='Add url to queue')
    parser.add_argument('-rl', '--remove-last', action='store_true', default=False, 
                        help='Remove last song from list')
    parser.add_argument('-p', '--play', action='store_true', default=False,
                        help='Play songs in queue')
    parser.add_argument('-c', '--clear', action='store_true', default=False,
                        help='Clear queue')
    parser.add_argument('-v', '--view', action='store_true', default=False,
                        help='View song in queue')
    args = parser.parse_args()
    parseArgs(args) 

if __name__ == '__main__':
    main()

